### PR TITLE
feat: script to setup ECU (fix libtracetool reference setting for pcl…

### PR DESCRIPTION
**Pull request by takeshi-iwanari**
…_ros)

Signed-off-by: takeshi.iwanari <takeshi.iwanari@tier4.jp>

# Why this change is needed

- To solve https://github.com/tier4/caret/issues/56 at field environment
- Normal user working at office can run the following commands to handle the issue
    ```
    source ~/ros2_caret_ws/install/local_setup.bash
    colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=Off -DCMAKE_CXX_FLAGS="-w"
    ```
- However, when we work at field environment like car, it becomes difficult to run these commands. and it will be handy to have scripts for it

# Considerations

- This repository may be inappropriate to contain such scripts, but I'd like to commit this scripts for now because we download this repository when using CARET
- Other settings (e.g. scripts to modify tmux script, autoware.env) will be added in the future

### CODE REVIEW

**Review by takam5f2 — APPROVED** [review]
LGTM!

**Comment by takeshi-iwanari** [comment]
@takam5f2 
Merging is blocked even though the commit has signed off and DCO check passed. It's probably because this repository setting `Require contributors to sign off on web-based commits`, so that GPG signature is also required.
Could you check the repository setting?
(I'm asking because I don't have the permission to change the setting in this repository)

**Comment by takam5f2** [comment]
@takeshi-iwanari  
Sorry for inconvenience. I fixed it. Could you check it again?

**Comment by takeshi-iwanari** [comment]
@takam5f2 
Thank you very much!

**Pull request merged**
